"""
DefenseOS - Alert Model
Alerts are generated by correlation rules applied to SecurityEvents.
They represent actionable items requiring analyst attention.
"""
import enum
from datetime import datetime, timezone

from sqlalchemy import DateTime, Enum, ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base


class AlertStatus(str, enum.Enum):
    OPEN = "open"
    INVESTIGATING = "investigating"
    RESOLVED = "resolved"
    FALSE_POSITIVE = "false_positive"


class AlertSeverity(str, enum.Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class Alert(Base):
    __tablename__ = "alerts"

    id: Mapped[int] = mapped_column(primary_key=True, index=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        index=True,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )
    title: Mapped[str] = mapped_column(String(512))
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    severity: Mapped[AlertSeverity] = mapped_column(
        Enum(AlertSeverity), default=AlertSeverity.MEDIUM, index=True
    )
    status: Mapped[AlertStatus] = mapped_column(
        Enum(AlertStatus), default=AlertStatus.OPEN, index=True
    )
    rule_name: Mapped[str | None] = mapped_column(String(128), nullable=True)
    source_event_id: Mapped[int | None] = mapped_column(
        Integer, ForeignKey("security_events.id", ondelete="SET NULL"), nullable=True
    )
    incident_id: Mapped[int | None] = mapped_column(
        Integer, ForeignKey("incidents.id", ondelete="SET NULL"), nullable=True
    )

    # Relationships
    incident: Mapped["Incident"] = relationship(  # noqa: F821
        "Incident", back_populates="alerts"
    )
